# coding: utf-8

"""
    Optimeering

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class EnumUnitType(str, Enum):
    """
    EnumUnitType
    """

    """
    allowed enum values
    """
    PRICE = "price"
    FLOW = "flow"
    CAPACITY = "capacity"
    VOLUME_RATIO_OF_PROCURED = "volume_ratio_of_procured"
    PRICE_SPREAD = "price_spread"
    DIRECTION = "direction"
    VOLUME = "volume"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EnumUnitType from a JSON string"""
        return cls(json.loads(json_str))
