# coding: utf-8

"""
    Optimeering

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class EnumProduct(str, Enum):
    """
    EnumProduct
    """

    """
    allowed enum values
    """
    MFRR_EAM_UP = "mFRR EAM Up"
    MFRR_EAM_DOWN = "mFRR EAM Down"
    AFRR_CM_UP = "aFRR CM Up"
    AFRR_CM_DOWN = "aFRR CM Down"
    AFRR_EAM_UP = "aFRR EAM Up"
    AFRR_EAM_DOWN = "aFRR EAM Down"
    IMBALANCE = "Imbalance"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EnumProduct from a JSON string"""
        return cls(json.loads(json_str))
